import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <h1 className="text-3xl font-bold font-open text-center mt-2">
              Next.js Full-Stack Boilerplate
          </h1>
      </main>

      <Footer />
    </div>
  );
}
